name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and Push the Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tinywell/blocklator
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./docker/Dockerfile
          tag_names: true
          cache: true
